export const FAQS_EN = [
  {
    title: "How do I start using the WordPress AI Text Summarizer Plugin?",
    content:
      `Then download and install the Text Summarizer Plugin from (<a href="https://buymeacoffee.com/dongyubin/e/257941" target="_blank" class="text-blue-600">here</a>) into your WordPress backend and add the Activation Code to start summarizing content.`,
  },
  {
    title: "How does the token usage work for the plugin?",
    content:
      "When you register for this WordPress plugin, you need to fill in the activation code. Once the activation code is filled in, you will be able to generate article summaries permanently.",
  },
  {
    title: "How can I use the summaries generated by the plugin?",
    content:
      `Text Summarizer makes it extremely easy to create and embed summaries within your content.  You can use it in 2 ways::
    <ul>
    <li>1. Generate blog post summaries with one click in the WordPress article list. This is the simplest way to generate and embed summaries. The summary operation can be completed with just one click.</li>
    <li>2. Create summaries via the dashboard. Once a summary is generated, you can simply copy it and use it wherever you need!</li>
    </ul>`,
  },
  {
    title: "Where will the summary generated by the plugin be displayed?",
    content:
      `The abstract content will be displayed in 2 places:
    <ul>
    <li>
      1. Display at the top of the front-end article content</li>
      <li>2. Display at the bottom of the back-end article editing page</li>
    </ul>`,
  },
  {
    title: "Can the article summary generated by AI be modified?",
    content:
      `It can be modified, just go to the backend article editing page and click on the <span class="text-blue-600">"Generate AI Summary"</span> button to regenerate the AI summary.`,
  },
  {
    title: "What if I encounter problems with the plugin?",
    content:
      `We're here to help! If you encounter any issues with the Text Summarizer Plugin, simply email us at <a href="mailto:itxh888@gmail.com">itxh888@gmail.com</a> and we will be happy to assist you. We're committed to ensuring a smooth and hassle-free experience for all our customers.`,
  },
];

export const FAQS_ZH = [
  {
    title: "如何开始使用 WordPress AI 文本摘要插件？",
    content:
      `然后从<a href="https://buymeacoffee.com/dongyubin/e/257941" target="_blank" class="text-blue-600">这里</a>下载并安装文本摘要插件到你的 WordPress 后台，并添加激活码以开始摘要内容。`,
  },
  {
    title: "插件的令牌使用是如何工作的？",
    content:
      "在你注册这个 WordPress 插件时，你需要填写激活码。填写激活码后，你将能够永久生成文章摘要。",
  },
  {
    title: "我如何使用插件生成的摘要？",
    content:
      `文本摘要器让你非常容易地在内容中创建和嵌入摘要。你可以通过两种方式使用它：
      <ul>
      <li>1. 在 WordPress 文章列表中一键生成博客文章摘要。这是生成和嵌入摘要的最简单方式，只需一键即可完成摘要操作。</li>
      <li>2. 通过仪表板创建摘要。生成摘要后，你可以简单地复制它并在你需要的地方使用！</li>
      </ul>`,
  },
  {
    title: "插件生成的摘要会显示在哪里？",
    content:
      `摘要内容将显示在两个地方：
      <ul>
      <li>1. 显示在前端文章内容的顶部</li>
      <li>2. 显示在后台文章编辑页面的底部</li>
      </ul>`,
  },
  {
    title: "AI 生成的文章摘要可以修改吗？",
    content:
      `可以修改，只需进入后台文章编辑页面，点击<span class="text-blue-600">"生成 AI 摘要"</span>按钮即可重新生成 AI 摘要。`,
  },
  {
    title: "如果我遇到插件问题怎么办？",
    content:
      `我们随时为你提供帮助！如果你遇到文本摘要插件的任何问题，请发送电子邮件至 <a href="mailto:itxh888@gmail.com">itxh888@gmail.com</a>，我们将很乐意为你提供帮助。我们致力于为所有客户提供顺畅和无忧的体验。`,
  },
];

export const FAQS_JA = [
  {
    title: "WordPress AI テキスト要約プラグインの使用を開始するにはどうすればよいですか？",
    content:
      `<a href="https://buymeacoffee.com/dongyubin/e/257941" target="_blank" class="text-blue-600">ここ</a>からテキスト要約プラグインをダウンロードしてインストールし、WordPress のバックエンドに追加してアクティベーションコードを追加してコンテンツの要約を開始します。`,
  },
  {
    title: "プラグインのトークンの使用方法はどのように機能しますか？",
    content:
      "この WordPress プラグインに登録すると、アクティベーションコードを入力する必要があります。アクティベーションコードを入力すると、永久に記事の要約を生成できるようになります。",
  },
  {
    title: "プラグインで生成された要約をどのように使用できますか？",
    content:
      `テキスト要約器を使用すると、コンテンツ内に非常に簡単に要約を作成して埋め込むことができます。2つの方法で使用できます：
      <ul>
      <li>1. WordPressの記事一覧でワンクリックでブログ記事の要約を生成する。これは最も簡単な要約生成方法であり、一回のクリックで要約操作が完了します。</li>
      <li>2. ダッシュボードを通じて要約を作成する。要約が生成されたら、コピーして必要な場所に使用するだけです！</li>
      </ul>`,
  },
  {
    title: "プラグインで生成された要約はどこに表示されますか？",
    content:
      `要約コンテンツは2箇所に表示されます：
      <ul>
      <li>1. フロントエンドの記事コンテンツの上部に表示されます</li>
      <li>2. バックエンドの記事編集ページの下部に表示されます</li>
      </ul>`,
  },
  {
    title: "AI が生成した記事の要約は修正できますか？",
    content:
      `修正できます。バックエンドの記事編集ページに移動し、<span class="text-blue-600">"AI 要約を生成"</span>ボタンをクリックして AI 要約を再生成します。`,
  },
  {
    title: "プラグインに問題があった場合はどうすればいいですか？",
    content:
      `私たちはお手伝いさせていただきます！テキスト要約プラグインに問題がある場合は、<a href="mailto:itxh888@gmail.com">itxh888@gmail.com</a> にメールを送ってください。喜んでお手伝いします。すべてのお客様がスムーズでトラブルのない体験を提供することをお約束します。`,
  },
];


export const FAQS_AR = [
  {
    title: "كيف أبدأ في استخدام مكون WordPress AI Text Summarizer الإضافي؟",
    content:
      `ثم قم بتنزيل وتثبيت مكون Text Summarizer الإضافي من (<a href="https://buymeacoffee.com/dongyubin/e/257941" target="_blank" class="text-blue-600">هنا</a>) في الواجهة الخلفية لـ WordPress الخاص بك وأضف رمز التفعيل للبدء في تلخيص المحتوى.`,
  },
  {
    title: "كيف يتم استخدام الرموز المميزة للمكون الإضافي؟",
    content:
      "عند التسجيل في هذا المكون الإضافي لـ WordPress، تحتاج إلى ملء رمز التفعيل. بمجرد إدخال رمز التفعيل، ستتمكن من إنشاء ملخصات المقالات بشكل دائم.",
  },
  {
    title: "كيف يمكنني استخدام الملخصات التي أنشأها المكون الإضافي؟",
    content:
      `يُسهل Text Summarizer إنشاء ودمج الملخصات في المحتوى الخاص بك. يمكنك استخدامه بطريقتين:
      <ul>
      <li>1. إنشاء ملخصات منشورات المدونات بنقرة واحدة في قائمة مقالات WordPress. هذه هي أبسط طريقة لإنشاء ودمج الملخصات. يمكن إكمال عملية التلخيص بنقرة واحدة فقط.</li>
      <li>2. إنشاء الملخصات عبر لوحة المعلومات. بمجرد إنشاء الملخص، يمكنك ببساطة نسخه واستخدامه في أي مكان تحتاجه!</li>
      </ul>`,
  },
  {
    title: "أين سيتم عرض الملخص المُنشأ بواسطة المكون الإضافي؟",
    content:
      `سيتم عرض المحتوى المختصر في مكانين:
      <ul>
      <li>1. عرض في أعلى محتوى المقالة في الواجهة الأمامية</li>
      <li>2. عرض أسفل صفحة تحرير المقالة في الواجهة الخلفية</li>
      </ul>`,
  },
  {
    title: "هل يمكن تعديل ملخص المقالة الذي تم إنشاؤه بواسطة الذكاء الاصطناعي؟",
    content:
      `يمكن تعديله، فقط اذهب إلى صفحة تحرير المقالة في الواجهة الخلفية وانقر على زر <span class="text-blue-600">"توليد ملخص الذكاء الاصطناعي"</span> لإعادة توليد ملخص الذكاء الاصطناعي.`,
  },
  {
    title: "ماذا أفعل إذا واجهت مشاكل مع المكون الإضافي؟",
    content:
      `نحن هنا للمساعدة! إذا واجهت أي مشاكل مع مكون Text Summarizer الإضافي، فقط أرسل لنا بريدًا إلكترونيًا إلى <a href="mailto:itxh888@gmail.com">itxh888@gmail.com</a> وسنكون سعداء بمساعدتك. نحن ملتزمون بضمان تجربة سلسة وخالية من المتاعب لجميع عملائنا.`,
  },
];

export const FAQS_ES = [
  {
    title: "¿Cómo funciona el uso de tokens para el complemento?",
    content:
      "Cuando te registras para este complemento de WordPress, necesitas llenar el código de activación. Una vez que se complete el código de activación, podrás generar resúmenes de artículos permanentemente.",
  },
  {
    title: "¿Cómo puedo utilizar los resúmenes generados por el complemento?",
    content:
      `Text Summarizer facilita mucho la creación e incorporación de resúmenes en tu contenido. Puedes usarlo de dos formas:
      <ul>
      <li>1. Genera resúmenes de publicaciones de blog con un solo clic en la lista de artículos de WordPress. Esta es la forma más sencilla de generar e incorporar resúmenes. La operación de resumen se puede completar con un solo clic.</li>
      <li>2. Crea resúmenes a través del panel de control. Una vez generado el resumen, puedes simplemente copiarlo y usarlo donde lo necesites.</li>
      </ul>`,
  },
  {
    title: "¿Dónde se mostrará el resumen generado por el complemento?",
    content:
      `El contenido del resumen se mostrará en dos lugares:
      <ul>
      <li>1. Mostrar en la parte superior del contenido del artículo en el front-end.</li>
      <li>2. Mostrar en la parte inferior de la página de edición del artículo en el back-end.</li>
      </ul>`,
  },
  {
    title: "¿Se puede modificar el resumen del artículo generado por la IA?",
    content:
      `Se puede modificar, solo ve a la página de edición del artículo en el back-end y haz clic en el botón <span class="text-blue-600">"Generar resumen AI"</span> para regenerar el resumen AI.`,
  },
  {
    title: "¿Qué debo hacer si encuentro problemas con el complemento?",
    content:
      `¡Estamos aquí para ayudarte! Si encuentras algún problema con el complemento Text Summarizer, simplemente envíanos un correo electrónico a <a href="mailto:itxh888@gmail.com">itxh888@gmail.com</a> y estaremos encantados de asistirte. Estamos comprometidos a garantizar una experiencia fluida y sin complicaciones para todos nuestros clientes.`,
  },
];


export const FAQS_RU = [
  {
    title: "Как начать использовать плагин WordPress AI Text Summarizer?",
    content:
      `Затем загрузите и установите плагин Text Summarizer с (<a href="https://buymeacoffee.com/dongyubin/e/257941" target="_blank" class="text-blue-600">этого сайта</a>) на ваш WordPress и добавьте код активации, чтобы начать подведение итогов контента.`,
  },
  {
    title: "Как работает использование токенов для плагина?",
    content:
      "При регистрации этого плагина WordPress вам нужно заполнить код активации. После заполнения кода активации вы сможете навсегда генерировать резюме статей.",
  },
  {
    title: "Как я могу использовать резюме, созданные плагином?",
    content:
      `Text Summarizer делает создание и встраивание резюме в ваш контент чрезвычайно простым. Вы можете использовать его двумя способами:
      <ul>
      <li>1. Генерируйте резюме блогов одним щелчком мыши в списке статей WordPress. Это самый простой способ генерировать и встраивать резюме. Операция суммирования может быть выполнена одним щелчком.</li>
      <li>2. Создавайте резюме через панель управления. После генерации резюме вы можете просто скопировать его и использовать в любом месте, где это необходимо!</li>
      </ul>`,
  },
  {
    title: "Где будет отображаться резюме, сгенерированное плагином?",
    content:
      `Содержание резюме будет отображаться в двух местах:
      <ul>
      <li>1. Отображение в верхней части содержимого статьи на фронт-энде</li>
      <li>2. Отображение в нижней части страницы редактирования статьи на бэк-энде</li>
      </ul>`,
  },
  {
    title: "Можно ли изменить резюме статьи, созданное AI?",
    content:
      `Можно изменить, просто перейдите на страницу редактирования статьи на бэк-энде и нажмите кнопку <span class="text-blue-600">"Создать резюме AI"</span>, чтобы заново сгенерировать резюме AI.`,
  },
  {
    title: "Что делать, если у меня возникли проблемы с плагином?",
    content:
      `Мы готовы помочь! Если у вас возникли проблемы с плагином Text Summarizer, просто отправьте нам письмо на <a href="mailto:itxh888@gmail.com">itxh888@gmail.com</a>, и мы будем рады вам помочь. Мы стремимся обеспечить плавный и беспроблемный опыт для всех наших клиентов.`,
  },
];

interface FAQSCollection {
  [key: `FAQS_${string}`]: {
    title: string;
    content: string;
  }[];
}
export const ALL_FAQS: FAQSCollection = {
  FAQS_EN,
  FAQS_ZH,
  FAQS_JA,
  FAQS_AR,
  FAQS_ES,
  FAQS_RU,
}